### ISSUE TITLE
Running the Consumer in while loop to wait for fragments to be triggered

### ISSUE THREAD

**Issue by S0UL4** [aws-samples/amazon-kinesis-video-streams-consumer-library-for-python#1]
Hi,
Thanks for this amazing Parser written in python.
I would like to know if i can run the Consumer in a while loop and waits for the producer to start sending.. Once the producer starts sending, it will be triggered and extract the different frames.
I have tried to add my_stream01_consumer.join() in the while loop of the service.loop function but it didn't work.
I also tried to put the function run() of the thread in a while loop.. but didn't work..
Thanks in advance.

**Comment by dcolcott** [comment]
Hi There

The parser thread (KvsConsumerLibrary) is designed to be ephemeral in that once spawned, it will run and then gracefully shut down once the media stream has no more fragments available. This way, the Thread status naturally follows the status of the media steam. The other intent is one parser thread acts as a worker to execute one stream request / operation. This approach keeps the thread pool clean and easy to manage. 

The .join() call only blocks while the Thread is alive so makes sense this doesn't work in the way you hoped.

There are a few solutions here:
1) You could catch the exiting KvsConsumerLibrary thread in the on_stream_read_complete callback and re-spawn a new thread until you have fragments arrive but is not a preferred option.

2)Using the same KVS Archive Media Client, call list_fragments API in a slow loop to check if any fragments are available before spawning the KvsConsumerLibrary thread or

3) Fork this Repo and add a check in KvsConsumerLibrary thread to avoid exiting the for read_chunk loop until at least a first fragment has arrived. 

Of the above I would recommend Option 2 as is light weight and is done in user application logic. i.e: it doesn't require you to run a custom fork of KvsConsumerLibrary. If you try Option 3 and update KvsConsumerLibrary feel free to submit back to this Repo as a PR.
