### ISSUE TITLE
how to send JPEGs to amazon rekognition?

### ISSUE THREAD

**Issue by PoojaR161** [aws-samples/amazon-kinesis-video-streams-consumer-library-for-python#3]
It's written as "JPEGs could also be sent to other AWS services such as Amazon Rekognition and Amazon Sagemaker" in the consumer library. Can you please help me on this.

**Comment by dcolcott** [comment]
HI Pooja,

There are 2 ways to do this: 

1) Using the Sagemaker boto3 Python SDK you can read the JPEG file as a blob and request the inference as described in below:
https://docs.aws.amazon.com/sagemaker/latest/dg/neo-requests-sdk.html
https://docs.aws.amazon.com/sagemaker/latest/dg/neo-requests-boto3.html

2) Send the image to Sagemaker runtime API directly as BASE64 encoded data as per: 
https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_runtime_InvokeEndpoint.html

Here is an example of that from an older post of mine:
https://github.com/awslabs/amazon-sagemaker-inference-client

This is in NodeJS but the API call is still demonstrated.

I'm working on an extension to this post to get PNG as blob data directly to save writing to disk first and get PNG as BASE64 that can be passed to Sagemaker / Rekognition, etc and will add some code examples to interact with these services. 

I will close this issue based on the existing solutions provided but also suggest to watch here for coming updates described. Thanks for the question. 

Regards,
Dean.

**Comment by PoojaR161** [comment]
Hello Dean,

Thanks for the reply. I will look into your suggestions.

Well, I was also trying to send the image files directly to Amazon Rekognition. And it's working after adding few lines of code.
Thank you for this fabulous 'consumer library', It's really helpful and easy to understand.

Regards,
Pooja
