### ISSUE TITLE
Official Python Impelementation?

### ISSUE THREAD

**Issue by Alex-Wenner-FHR** [aws-samples/amazon-kinesis-video-streams-consumer-library-for-python#5]
Hi, thanks for the library. Doing this in python opens the door for ease of use when integrating with CV.

Is it fair to say that this is an official implementation of a KVS consumer? 

If so, any way that this could be refactored a bit and shipped as an sdk on pypi? Similar to what AWS has done with their Java Parser?

This is great but it ships a bit heavy having to clone the entire repo, edit files, and include in a local/remote folder to be able to make use of this implementation!

**Comment by dcolcott** [comment]
Hi Alex,

This is unofficial in that its community supported opposed to officially supported by the AWS Kinesis Video Service itself. That being said, is no reason it can't be packaged in PyPi with a similar support model.

As time permits I will publish as a PyPi package.

Regards,
Dean.
